### ISSUE TITLE
How do I upgrade v1 to v2 ?

### ISSUE THREAD

**Issue by dohq** [pivotal-cf/credhub-release#33]
What version of the credhub server you are using?
1.9.9

What version of the credhub cli you are using?
1.7.7

If you were attempting to accomplish a task, what was it you were attempting to do?
upgrade 1.9.9 to 2.1.2
(credhub colocated concourse web)

What did you expect to happen?
failed `bosh deploy`
output pre-start.stderr.log
```
panic: Internal providers require encryption_password.

goroutine 1 [running]:
main.main()
        /var/vcap/data/compile/configurator/src/configurator/main.go:101 +0x18f6
```

What was the actual behavior?
bosh deploy manifest chang url/varsion/hash

This deploy manifests
```
- type: replace
  path: /releases/-
  value:
    name: credhub
    url: https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=1.9.9
    version: 1.9.9
    sha1: 965877dbbf48bd300326ea8f3a548875f97868bd

- type: replace
  path: /instance_groups/name=web/jobs/name=atc/properties/credhub?
  value:
    url: https://localhost:8844
    client_id: ((credhub_client_id))
    client_secret: ((credhub_client_secret))
    tls:
      insecure_skip_verify: true
      ca_cert:
        certificate: ((credhub-tls.ca))

- type: replace
  path: /instance_groups/name=web/jobs/0:before
  value:
    name: credhub
    release: credhub
    properties:
      credhub:
        tls: ((credhub-tls))
        authorization:
          acls:
            enabled: true
        authentication:
          uaa:
            url: ((uaa-url))
            ca_certs:
            - ((uaa-tls.ca))
        data_storage:
          type: postgres
          username: credhub
          password: ((credhub-db-password))
          database: credhub
          require_tls: false
        encryption:
          keys: 
          - provider_name: int
            encryption_password: ((credhub-encryption-password))
            active: true
          providers: 
          - name: int
            type: internal

- type: replace
  path: /instance_groups/name=db/jobs/name=postgres/properties/databases/databases/-
  value:
    name: credhub

- type: replace
  path: /instance_groups/name=db/jobs/name=postgres/properties/databases/roles/-
  value: 
    name: credhub
    password: ((credhub-db-password))

- type: replace
  path: /variables/-
  value:
    name: credhub-tls
    type: certificate
    options:
      ca: atc_ca
      common_name: localhost:8844
      alternative_names:
      - 127.0.0.1

- type: replace
  path: /variables/-
  value:
    name: credhub-db-password
    type: password

- type: replace
  path: /variables/-
  value:
    name: credhub-encryption-password
    type: password
    options:
      length: 40
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction
